plugins {
    id 'java'
    id 'application'
    id 'checkstyle'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.12.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'org.cache.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

test {
    useJUnitPlatform()
    systemProperty 'net.bytebuddy.experimental', 'true'
}

checkstyle {
    configFile = file('config/checkstyle/checkstyle.xml')
}